sources:
  - temp/ChocolateClassicalSans-Regular.ufo
familyName: "Chocolate Classical Sans"
# some glyphs from new source has overlaps
removeOutlineOverlaps: True
extraFontmakeArgs: "--production-names --overlaps-backend pathops"
autohintOTF: False
autohintTTF: False
buildWebfont: False
buildSmallCap: False
version: 1.005    # For some reason FC is exporting a weird version string
